// evidence-fixtures.ts — Seed fixture data for evidence-driven decisions

import type {
  PredictionBrief,
  PredictionMarketEvidence,
} from "./prediction-types.js";
import type {
  AccountTierLabel,
  ContentPerformanceFeatures,
  ContentStructureFeatures,
  ObservedAccount,
  ObservedContent,
  SupportedTrendPlatform,
  TopicMomentumLabel,
  TrendOpportunity,
} from "./trend-monitoring-types.js";

export type LowFollowerSource = {
  id: string;
  platform: string;
  contentForm: string;
  title: string;
  account: string;
  fansLabel: string;
  fansCount: number;
  anomaly: number;
  playCount: string;
  trackTags: string[];
  suggestion: string;
  publishedAt: string;
};

export type SeedAccount = ObservedAccount & { whyIncluded: string };
export type SeedContent = ObservedContent & {
  authorName: string;
  whyIncluded: string;
  structureSummary: string;
};

export interface TrendSeedFixture {
  id: string;
  matchers: RegExp[];
  trend: TrendOpportunity;
  tierBreakdown: PredictionMarketEvidence["tierBreakdown"];
  accounts: SeedAccount[];
  contents: SeedContent[];
  evidenceGaps?: string[];
}

export const PLATFORM_LABELS: Record<SupportedTrendPlatform, string> = {
  douyin: "抖音",
  xiaohongshu: "小红书",
  kuaishou: "快手",
};

export const TIER_LABELS: Record<AccountTierLabel, string> = {
  head_kol: "头部 KOL",
  standard_kol: "标准 KOL",
  strong_koc: "强 KOC",
  standard_koc: "标准 KOC",
  watch_account: "观察账号",
};

export const MOMENTUM_LABELS: Record<TopicMomentumLabel, string> = {
  emerging: "新出现",
  accelerating: "加速放量",
  crowded: "竞争拥挤",
  cooling: "开始降温",
};

export function accountPerformance(
  followerCount: number | null,
  avgEngagementRate30d: number | null,
  breakoutHitRate30d: number | null,
) {
  return {
    followerCount,
    contentCount30d: 18,
    avgEngagementRate30d,
    engagementPer1kFollowers30d:
      followerCount && avgEngagementRate30d
        ? Math.round(avgEngagementRate30d * 10)
        : null,
    postingFrequency30d: 4.2,
    breakoutHitRate30d,
  };
}

export function contentPerformance(
  publishedAt: string,
  viewCount: number | null,
  likeCount: number | null,
  commentCount: number | null,
  shareCount: number | null,
  commentQuestionClusters: string[],
): ContentPerformanceFeatures {
  return {
    publishedAt,
    viewCount,
    likeCount,
    commentCount,
    shareCount,
    engagementPer1kFollowers: null,
    commentQuestionClusters,
  };
}

export function contentStructure(
  hookType: string,
  narrativePattern: string,
  visualFormat: string,
  durationBucket: string,
): ContentStructureFeatures {
  return {
    hookType,
    narrativePattern,
    visualFormat,
    durationBucket,
  };
}

const WORKPLACE_FIXTURE: TrendSeedFixture = {
  id: "workplace",
  matchers: [/职场/, /excel/i, /办公/, /面试/, /求职/, /入职/],
  trend: {
    trendId: "trend-workplace-efficiency",
    industryId: "industry-workplace",
    industryName: "职场教育",
    platform: "douyin",
    topicCluster: "职场新人效率提效",
    momentumLabel: "accelerating",
    evidenceWindow: {
      startAt: "2026-03-10T00:00:00+08:00",
      endAt: "2026-03-24T23:59:59+08:00",
      lookbackDays: 14,
    },
    kolCount: 14,
    kocCount: 42,
    newCreatorCount: 19,
    similarContentCount: 87,
    growth7d: 34,
    lowFollowerAnomalyRatio: 0.28,
    competitionScore: 63,
    opportunityScore: 78,
    riskScore: 54,
    timingLabel: "问题词还在抬升，窗口未被头部完全占满",
    whyNow:
      "新人入职、面试和办公效率需求叠加，搜索意图和低粉异常样本同时在增长。",
    whyRisky: "泛教程已经拥挤，必须缩到具体场景和结果承诺。",
    recommendedAction: "用一条场景型内容快速验证，跑通后直接转成连续系列。",
    evidence: {
      supportingAccountIds: [
        "acct-job-rookie",
        "acct-hr-playbook",
        "acct-excel-punchline",
      ],
      supportingContentIds: [
        "content-job-first-week",
        "content-excel-report",
        "content-hr-question",
      ],
      lowFollowerSampleIds: ["f1", "g2", "g9"],
    },
    accountTierRuleVersion: "account-tier-rules.v1",
    trendDetectionRuleVersion: "trend-detection.v1",
    scoreEngineVersion: "score-engine.v1",
  },
  tierBreakdown: {
    headKol: 1,
    standardKol: 13,
    strongKoc: 16,
    standardKoc: 26,
  },
  accounts: [
    {
      accountId: "acct-job-rookie",
      platform: "douyin",
      handle: "入职第一周笔记",
      displayName: "入职第一周笔记",
      industryId: "industry-workplace",
      tierLabel: "strong_koc",
      performance: accountPerformance(36800, 7.8, 0.28),
      recentTopicClusters: ["新人入职", "办公效率", "汇报技巧"],
      whyIncluded: "低粉体量下多次跑出新人视角内容，说明场景切口存在复制空间。",
    },
    {
      accountId: "acct-hr-playbook",
      platform: "douyin",
      handle: "HR避坑指南",
      displayName: "HR 避坑指南",
      industryId: "industry-workplace",
      tierLabel: "standard_kol",
      performance: accountPerformance(246000, 5.2, 0.18),
      recentTopicClusters: ["面试问题", "求职表达", "职场避坑"],
      whyIncluded: "稳定覆盖问题词搜索流量，可验证用户当前到底在搜什么。",
    },
    {
      accountId: "acct-excel-punchline",
      platform: "douyin",
      handle: "Excel 结果派",
      displayName: "Excel 结果派",
      industryId: "industry-workplace",
      tierLabel: "standard_koc",
      performance: accountPerformance(18400, 8.6, 0.24),
      recentTopicClusters: ["Excel 快捷键", "汇报提效", "新人模板"],
      whyIncluded: "不是纯教程号，而是围绕结果承诺做结构化表达，和当前机会高度一致。",
    },
  ],
  contents: [
    {
      contentId: "content-job-first-week",
      platform: "douyin",
      authorId: "acct-job-rookie",
      authorName: "入职第一周笔记",
      industryId: "industry-workplace",
      topicCluster: "职场新人效率提效",
      title: "入职第一周最容易踩坑的 3 个汇报动作",
      keywordTokens: ["入职", "汇报", "避坑"],
      tags: ["职场", "新人", "效率"],
      structure: contentStructure("反常识开头", "三步拆解", "口播 + 屏录", "60-90s"),
      structureSummary: "先给错误动作，再给替代模板，最后补汇报结果。",
      performance: contentPerformance(
        "2026-03-21T20:15:00+08:00",
        183000,
        11200,
        680,
        1240,
        ["汇报模板", "第一周", "被领导夸"],
      ),
      whyIncluded: "标题和评论都围绕明确场景，说明泛职场内容已经向具体问题收缩。",
    },
    {
      contentId: "content-excel-report",
      platform: "douyin",
      authorId: "acct-excel-punchline",
      authorName: "Excel 结果派",
      industryId: "industry-workplace",
      topicCluster: "职场新人效率提效",
      title: "这 1 个 Excel 公式，能把日报时间从 40 分钟压到 8 分钟",
      keywordTokens: ["Excel", "日报", "效率"],
      tags: ["Excel", "办公", "职场"],
      structure: contentStructure("先给结果", "步骤证明", "屏录", "30-60s"),
      structureSummary: "结果先行 + 操作证明 + 适用对象，典型高转化工具型结构。",
      performance: contentPerformance(
        "2026-03-20T09:30:00+08:00",
        132000,
        8400,
        420,
        900,
        ["日报公式", "新手", "效率提升"],
      ),
      whyIncluded: "不是炫技公式，而是明确结果承诺，更接近用户当下的真实搜索意图。",
    },
    {
      contentId: "content-hr-question",
      platform: "douyin",
      authorId: "acct-hr-playbook",
      authorName: "HR 避坑指南",
      industryId: "industry-workplace",
      topicCluster: "职场新人效率提效",
      title: "HR 最想追问的 3 个面试问题，你别再用套话回答",
      keywordTokens: ["HR", "面试", "套话"],
      tags: ["求职", "面试", "沟通"],
      structure: contentStructure("高频问题开头", "对比纠错", "口播", "60-90s"),
      structureSummary: "用户问题驱动的纠错型结构，评论区验证了问题词持续存在。",
      performance: contentPerformance(
        "2026-03-18T18:20:00+08:00",
        214000,
        12800,
        1090,
        1640,
        ["面试问题", "套话", "真实回答"],
      ),
      whyIncluded: "评论里反复出现“还有哪些问题”，说明用户需求还在扩散。",
    },
  ],
};

const PET_FIXTURE: TrendSeedFixture = {
  id: "pet",
  matchers: [/宠物/, /萌宠/, /猫/, /狗/],
  trend: {
    trendId: "trend-pet-series",
    industryId: "industry-pet",
    industryName: "宠物日常",
    platform: "xiaohongshu",
    topicCluster: "宠物人格化日常",
    momentumLabel: "accelerating",
    evidenceWindow: {
      startAt: "2026-03-11T00:00:00+08:00",
      endAt: "2026-03-24T23:59:59+08:00",
      lookbackDays: 14,
    },
    kolCount: 18,
    kocCount: 57,
    newCreatorCount: 24,
    similarContentCount: 96,
    growth7d: 39,
    lowFollowerAnomalyRatio: 0.16,
    competitionScore: 49,
    opportunityScore: 83,
    riskScore: 36,
    timingLabel: "人格化叙事在双平台都还在持续抬升",
    whyNow: "用户不只看萌点，而在追关系感和固定角色日常。",
    whyRisky: "如果只有零散素材，没有连续叙事，关注很难沉淀。",
    recommendedAction: "直接生成系列测试 brief，优先跑栏目感。",
    evidence: {
      supportingAccountIds: ["acct-pet-siblings", "acct-pet-clinic", "acct-pet-diary"],
      supportingContentIds: ["content-pet-breakfast", "content-pet-clinic", "content-pet-weekend"],
      lowFollowerSampleIds: [],
    },
    accountTierRuleVersion: "account-tier-rules.v1",
    trendDetectionRuleVersion: "trend-detection.v1",
    scoreEngineVersion: "score-engine.v1",
  },
  tierBreakdown: {
    headKol: 2,
    standardKol: 16,
    strongKoc: 21,
    standardKoc: 36,
  },
  accounts: [
    {
      accountId: "acct-pet-siblings",
      platform: "xiaohongshu",
      handle: "猫狗兄妹日常",
      displayName: "猫狗兄妹日常",
      industryId: "industry-pet",
      tierLabel: "standard_koc",
      performance: accountPerformance(42800, 9.4, 0.32),
      recentTopicClusters: ["宠物人格", "日常互动", "固定栏目"],
      whyIncluded: "不是单条萌宠爆点，而是稳定靠角色关系感拿到收藏和回访。",
    },
    {
      accountId: "acct-pet-clinic",
      platform: "douyin",
      handle: "宠物门诊观察室",
      displayName: "宠物门诊观察室",
      industryId: "industry-pet",
      tierLabel: "standard_kol",
      performance: accountPerformance(312000, 4.9, 0.15),
      recentTopicClusters: ["宠物科普", "照护误区", "病例故事"],
      whyIncluded: "说明知识型角色也能承接这波窗口，但需要人设和系列感。",
    },
    {
      accountId: "acct-pet-diary",
      platform: "douyin",
      handle: "柴犬观察日记",
      displayName: "柴犬观察日记",
      industryId: "industry-pet",
      tierLabel: "strong_koc",
      performance: accountPerformance(22600, 10.8, 0.29),
      recentTopicClusters: ["宠物日常", "角色口吻", "连续剧情"],
      whyIncluded: "小体量账号也能吃到系列叙事红利，验证了可复制性。",
    },
  ],
  contents: [
    {
      contentId: "content-pet-breakfast",
      platform: "xiaohongshu",
      authorId: "acct-pet-siblings",
      authorName: "猫狗兄妹日常",
      industryId: "industry-pet",
      topicCluster: "宠物人格化日常",
      title: "今天又是狗哥偷吃猫妹早餐的一天",
      keywordTokens: ["早餐", "偷吃", "猫狗兄妹"],
      tags: ["宠物", "日常", "系列"],
      structure: contentStructure("冲突开头", "日常剧情", "图文", "图文"),
      structureSummary: "固定角色 + 轻冲突 + 结尾互动，适合系列连续更新。",
      performance: contentPerformance(
        "2026-03-20T08:40:00+08:00",
        168000,
        18900,
        860,
        2100,
        ["太像小孩了", "想看下一集"],
      ),
      whyIncluded: "收藏和评论都在追后续，说明真正跑起来的是关系感而不是单次萌点。",
    },
    {
      contentId: "content-pet-clinic",
      platform: "douyin",
      authorId: "acct-pet-clinic",
      authorName: "宠物门诊观察室",
      industryId: "industry-pet",
      topicCluster: "宠物人格化日常",
      title: "猫咪一整天不吃饭，最容易被忽视的其实不是肠胃",
      keywordTokens: ["猫咪", "不吃饭", "误区"],
      tags: ["宠物", "科普", "误区"],
      structure: contentStructure("问题开头", "误区纠正", "口播", "60-90s"),
      structureSummary: "强问题词 + 人设可信度，证明角色型账号也能承接需求流量。",
      performance: contentPerformance(
        "2026-03-18T22:00:00+08:00",
        241000,
        14000,
        1320,
        1780,
        ["我家猫也这样", "怎么判断"],
      ),
      whyIncluded: "说明宠物赛道不止情绪内容，问题型知识内容也在共享同一窗口。",
    },
    {
      contentId: "content-pet-weekend",
      platform: "douyin",
      authorId: "acct-pet-diary",
      authorName: "柴犬观察日记",
      industryId: "industry-pet",
      topicCluster: "宠物人格化日常",
      title: "周末想睡懒觉，但柴犬已经把我今天安排好了",
      keywordTokens: ["周末", "柴犬", "懒觉"],
      tags: ["宠物", "生活", "剧情"],
      structure: contentStructure("反差开头", "一日剧情", "vlog", "30-60s"),
      structureSummary: "用主人视角承接宠物人格，适合连续更新和栏目化。",
      performance: contentPerformance(
        "2026-03-23T10:00:00+08:00",
        119000,
        9600,
        420,
        1110,
        ["像拍综艺", "这个系列可以继续"],
      ),
      whyIncluded: "说明“宠物像人一样生活”仍然有连续消费价值。",
    },
  ],
};

const FOOD_FIXTURE: TrendSeedFixture = {
  id: "food",
  matchers: [/美食/, /探店/, /餐厅/, /吃/],
  trend: {
    trendId: "trend-food-revisit",
    industryId: "industry-food",
    industryName: "美食探店",
    platform: "douyin",
    topicCluster: "回访型本地探店",
    momentumLabel: "emerging",
    evidenceWindow: {
      startAt: "2026-03-10T00:00:00+08:00",
      endAt: "2026-03-24T23:59:59+08:00",
      lookbackDays: 14,
    },
    kolCount: 9,
    kocCount: 31,
    newCreatorCount: 17,
    similarContentCount: 58,
    growth7d: 21,
    lowFollowerAnomalyRatio: 0.24,
    competitionScore: 72,
    opportunityScore: 68,
    riskScore: 61,
    timingLabel: "同城需求还在，但模板型探店已经很挤",
    whyNow: "回访、适合谁、不适合谁等信号开始替代一次性价格刺激。",
    whyRisky: "泛探店模板高度同质化，结构没拆清就容易撞车。",
    recommendedAction: "先做爆款拆解，找到真正可借的结构部件。",
    evidence: {
      supportingAccountIds: ["acct-city-revisit", "acct-local-koc", "acct-weekend-eat"],
      supportingContentIds: ["content-city-revisit", "content-late-night-food", "content-price-proof"],
      lowFollowerSampleIds: ["f2", "g8"],
    },
    accountTierRuleVersion: "account-tier-rules.v1",
    trendDetectionRuleVersion: "trend-detection.v1",
    scoreEngineVersion: "score-engine.v1",
  },
  tierBreakdown: {
    headKol: 0,
    standardKol: 9,
    strongKoc: 11,
    standardKoc: 20,
  },
  accounts: [
    {
      accountId: "acct-city-revisit",
      platform: "douyin",
      handle: "同城回访笔记",
      displayName: "同城回访笔记",
      industryId: "industry-food",
      tierLabel: "strong_koc",
      performance: accountPerformance(22600, 8.1, 0.26),
      recentTopicClusters: ["回访证明", "人均预算", "适合谁"],
      whyIncluded: "低粉账号靠回访证据拿到明显高于模板探店的互动效率。",
    },
    {
      accountId: "acct-local-koc",
      platform: "xiaohongshu",
      handle: "本地吃饭研究所",
      displayName: "本地吃饭研究所",
      industryId: "industry-food",
      tierLabel: "standard_koc",
      performance: accountPerformance(12800, 11.2, 0.34),
      recentTopicClusters: ["小馆回访", "人均预算", "避雷"],
      whyIncluded: "说明“回访 + 预算 + 避雷”是一种跨平台可迁移结构。",
    },
    {
      accountId: "acct-weekend-eat",
      platform: "douyin",
      handle: "周末吃点啥",
      displayName: "周末吃点啥",
      industryId: "industry-food",
      tierLabel: "standard_kol",
      performance: accountPerformance(142000, 4.8, 0.14),
      recentTopicClusters: ["同城美食", "周末探店", "人群推荐"],
      whyIncluded: "中腰部账号也在向“适合谁/不适合谁”表达方式迁移。",
    },
  ],
  contents: [
    {
      contentId: "content-city-revisit",
      platform: "douyin",
      authorId: "acct-city-revisit",
      authorName: "同城回访笔记",
      industryId: "industry-food",
      topicCluster: "回访型本地探店",
      title: "这家我一周去了 3 次，只有这 2 道菜值得点",
      keywordTokens: ["回访", "值得点", "同城"],
      tags: ["探店", "回访", "同城"],
      structure: contentStructure("回访结果开头", "优劣对比", "竖屏视频", "30-60s"),
      structureSummary: "先交代回访次数，再给明确选择，减少“广告感”。",
      performance: contentPerformance(
        "2026-03-22T20:20:00+08:00",
        158000,
        9100,
        560,
        1230,
        ["这家真能打吗", "适合约会吗"],
      ),
      whyIncluded: "跑起来的不是店名，而是“回访 + 选择”结构本身。",
    },
    {
      contentId: "content-late-night-food",
      platform: "xiaohongshu",
      authorId: "acct-local-koc",
      authorName: "本地吃饭研究所",
      industryId: "industry-food",
      topicCluster: "回访型本地探店",
      title: "下班后 30 元内能吃舒服的 3 家店，我真的都回去过",
      keywordTokens: ["下班后", "30元", "回去过"],
      tags: ["探店", "预算", "本地"],
      structure: contentStructure("明确预算开头", "清单推荐", "图文", "图文"),
      structureSummary: "预算 + 场景 + 回访证明，适合收藏型平台传播。",
      performance: contentPerformance(
        "2026-03-19T19:10:00+08:00",
        92000,
        11600,
        380,
        980,
        ["适合打工人", "求南城版本"],
      ),
      whyIncluded: "证明同城用户更愿意为“适合自己”而不是“这家店很火”买单。",
    },
    {
      contentId: "content-price-proof",
      platform: "douyin",
      authorId: "acct-weekend-eat",
      authorName: "周末吃点啥",
      industryId: "industry-food",
      topicCluster: "回访型本地探店",
      title: "别再信网红套餐了，这家店真正值得的是这个 28 元双人搭配",
      keywordTokens: ["网红套餐", "28元", "双人"],
      tags: ["探店", "价格", "避雷"],
      structure: contentStructure("反套路开头", "价格证据", "口播 + 出镜", "60-90s"),
      structureSummary: "反套路 + 明确价格锚点，更容易建立可信度和转化欲望。",
      performance: contentPerformance(
        "2026-03-17T18:50:00+08:00",
        176000,
        8400,
        620,
        1310,
        ["这个套餐真实存在吗", "适合两个人吗"],
      ),
      whyIncluded: "结构重点是价格锚点和避雷，而不是泛探店镜头。",
    },
  ],
};

const FITNESS_FIXTURE: TrendSeedFixture = {
  id: "fitness",
  matchers: [/健身/, /体脂/, /减脂/, /训练/],
  trend: {
    trendId: "trend-fitness-record",
    industryId: "industry-fitness",
    industryName: "健身减脂",
    platform: "douyin",
    topicCluster: "结果记录型减脂",
    momentumLabel: "accelerating",
    evidenceWindow: {
      startAt: "2026-03-09T00:00:00+08:00",
      endAt: "2026-03-24T23:59:59+08:00",
      lookbackDays: 16,
    },
    kolCount: 16,
    kocCount: 29,
    newCreatorCount: 15,
    similarContentCount: 62,
    growth7d: 33,
    lowFollowerAnomalyRatio: 0.22,
    competitionScore: 58,
    opportunityScore: 80,
    riskScore: 44,
    timingLabel: "季节性减脂需求和结果记录内容同步走强",
    whyNow: "用户正在找能给过程证据和阶段结果的人，而不是泛建议。",
    whyRisky: "没有连续记录和结果证据时，很容易只剩观点层竞争。",
    recommendedAction: "先对标账号打法，再决定谁来吃这波机会。",
    evidence: {
      supportingAccountIds: ["acct-fatloss-log", "acct-office-train", "acct-postpartum-fit"],
      supportingContentIds: ["content-fatloss-30d", "content-office-train", "content-plateau-fix"],
      lowFollowerSampleIds: ["f3"],
    },
    accountTierRuleVersion: "account-tier-rules.v1",
    trendDetectionRuleVersion: "trend-detection.v1",
    scoreEngineVersion: "score-engine.v1",
  },
  tierBreakdown: {
    headKol: 1,
    standardKol: 15,
    strongKoc: 13,
    standardKoc: 16,
  },
  accounts: [
    {
      accountId: "acct-fatloss-log",
      platform: "douyin",
      handle: "体脂管理日记",
      displayName: "体脂管理日记",
      industryId: "industry-fitness",
      tierLabel: "strong_koc",
      performance: accountPerformance(35800, 8.4, 0.31),
      recentTopicClusters: ["30天减脂", "饮食记录", "体重变化"],
      whyIncluded: "低粉账号已经证明“阶段数据 + 真过程”比泛训练建议更能跑。",
    },
    {
      accountId: "acct-office-train",
      platform: "xiaohongshu",
      handle: "上班族减脂备忘录",
      displayName: "上班族减脂备忘录",
      industryId: "industry-fitness",
      tierLabel: "standard_koc",
      performance: accountPerformance(18600, 9.7, 0.27),
      recentTopicClusters: ["上班族减脂", "午休训练", "体脂变化"],
      whyIncluded: "说明细分人群和记录型表达组合仍有显著空间。",
    },
    {
      accountId: "acct-postpartum-fit",
      platform: "douyin",
      handle: "产后恢复进度条",
      displayName: "产后恢复进度条",
      industryId: "industry-fitness",
      tierLabel: "standard_kol",
      performance: accountPerformance(204000, 5.6, 0.17),
      recentTopicClusters: ["产后恢复", "围度变化", "饮食复盘"],
      whyIncluded: "中腰部账号跑起来的关键也是过程结果，而不是大而泛的健身观点。",
    },
  ],
  contents: [
    {
      contentId: "content-fatloss-30d",
      platform: "douyin",
      authorId: "acct-fatloss-log",
      authorName: "体脂管理日记",
      industryId: "industry-fitness",
      topicCluster: "结果记录型减脂",
      title: "30 天体脂降到 21%，我只改了晚饭这一个动作",
      keywordTokens: ["30天", "体脂", "晚饭"],
      tags: ["减脂", "记录", "结果"],
      structure: contentStructure("结果先行", "原因拆解", "口播", "30-60s"),
      structureSummary: "明确时间跨度 + 单点动作解释，是当前最稳的结果记录结构。",
      performance: contentPerformance(
        "2026-03-18T08:20:00+08:00",
        264000,
        18600,
        1240,
        2280,
        ["怎么吃", "能坚持吗", "想看完整过程"],
      ),
      whyIncluded: "说明用户要的不是泛训练建议，而是可模仿的单点改变量。",
    },
    {
      contentId: "content-office-train",
      platform: "xiaohongshu",
      authorId: "acct-office-train",
      authorName: "上班族减脂备忘录",
      industryId: "industry-fitness",
      topicCluster: "结果记录型减脂",
      title: "午休 20 分钟做这套，3 周腰围少了 4cm",
      keywordTokens: ["午休", "腰围", "3周"],
      tags: ["减脂", "上班族", "训练"],
      structure: contentStructure("场景开头", "短流程示范", "图文", "图文"),
      structureSummary: "场景限制 + 阶段结果，适合收藏和后续复做。",
      performance: contentPerformance(
        "2026-03-20T12:00:00+08:00",
        118000,
        13200,
        460,
        910,
        ["办公室能做吗", "收藏了晚点练"],
      ),
      whyIncluded: "证明细分人群和可执行限制，会显著提高转化意图。",
    },
    {
      contentId: "content-plateau-fix",
      platform: "douyin",
      authorId: "acct-postpartum-fit",
      authorName: "产后恢复进度条",
      industryId: "industry-fitness",
      topicCluster: "结果记录型减脂",
      title: "减脂卡住不是练少了，而是你根本没算对这个量",
      keywordTokens: ["卡住", "减脂平台期", "量"],
      tags: ["减脂", "平台期", "方法"],
      structure: contentStructure("误区开头", "纠偏解释", "口播", "60-90s"),
      structureSummary: "强问题词 + 纠偏，兼顾流量和专业感。",
      performance: contentPerformance(
        "2026-03-22T19:30:00+08:00",
        203000,
        12100,
        980,
        1710,
        ["终于知道为什么没掉秤", "能不能出完整菜单"],
      ),
      whyIncluded: "说明用户对过程数据和纠偏解释有强烈持续需求。",
    },
  ],
};

const EMOTION_FIXTURE: TrendSeedFixture = {
  id: "emotion",
  matchers: [/情感/, /女性/, /分手/, /内耗/, /关系/],
  trend: {
    trendId: "trend-emotion-stage",
    industryId: "industry-emotion",
    industryName: "情绪成长",
    platform: "xiaohongshu",
    topicCluster: "阶段型情绪叙事",
    momentumLabel: "accelerating",
    evidenceWindow: {
      startAt: "2026-03-08T00:00:00+08:00",
      endAt: "2026-03-24T23:59:59+08:00",
      lookbackDays: 17,
    },
    kolCount: 11,
    kocCount: 48,
    newCreatorCount: 21,
    similarContentCount: 73,
    growth7d: 37,
    lowFollowerAnomalyRatio: 0.19,
    competitionScore: 51,
    opportunityScore: 84,
    riskScore: 41,
    timingLabel: "阶段性情绪表达仍在放量，泛鸡汤开始疲劳",
    whyNow: "阶段、处境和自我修复路径正在替代抽象金句。",
    whyRisky: "如果没有明确阶段和处境，内容很容易回到泛共鸣竞争。",
    recommendedAction: "直接生成系列测试 brief，优先跑阶段叙事。",
    evidence: {
      supportingAccountIds: ["acct-breakup-log", "acct-growth-notes", "acct-midlife-reset"],
      supportingContentIds: ["content-breakup-week3", "content-boundary", "content-midlife-reset"],
      lowFollowerSampleIds: ["g1", "g7"],
    },
    accountTierRuleVersion: "account-tier-rules.v1",
    trendDetectionRuleVersion: "trend-detection.v1",
    scoreEngineVersion: "score-engine.v1",
  },
  tierBreakdown: {
    headKol: 1,
    standardKol: 10,
    strongKoc: 20,
    standardKoc: 28,
  },
  accounts: [
    {
      accountId: "acct-breakup-log",
      platform: "xiaohongshu",
      handle: "分手恢复练习册",
      displayName: "分手恢复练习册",
      industryId: "industry-emotion",
      tierLabel: "strong_koc",
      performance: accountPerformance(31200, 12.4, 0.33),
      recentTopicClusters: ["分手第几周", "情绪清单", "恢复过程"],
      whyIncluded: "低粉账号已经证明阶段叙事比泛鸡汤更容易拿到收藏和私信。",
    },
    {
      accountId: "acct-growth-notes",
      platform: "xiaohongshu",
      handle: "女生关系边界课",
      displayName: "女生关系边界课",
      industryId: "industry-emotion",
      tierLabel: "standard_kol",
      performance: accountPerformance(168000, 6.2, 0.19),
      recentTopicClusters: ["关系边界", "女性成长", "表达模板"],
      whyIncluded: "说明“阶段 + 工具”组合比纯情绪表达更强。",
    },
    {
      accountId: "acct-midlife-reset",
      platform: "xiaohongshu",
      handle: "中年重启手册",
      displayName: "中年重启手册",
      industryId: "industry-emotion",
      tierLabel: "standard_koc",
      performance: accountPerformance(22400, 8.9, 0.27),
      recentTopicClusters: ["重建自己", "关系恢复", "人生阶段"],
      whyIncluded: "视频号侧也在验证阶段叙事窗口，不只是单平台现象。",
    },
  ],
  contents: [
    {
      contentId: "content-breakup-week3",
      platform: "xiaohongshu",
      authorId: "acct-breakup-log",
      authorName: "分手恢复练习册",
      industryId: "industry-emotion",
      topicCluster: "阶段型情绪叙事",
      title: "分手后第 3 周，我才发现最难的不是想他",
      keywordTokens: ["分手后第3周", "恢复", "阶段"],
      tags: ["情感", "成长", "阶段"],
      structure: contentStructure("阶段开头", "独白 + 清单", "图文", "图文"),
      structureSummary: "明确阶段 + 内心变化 + 可收藏清单，是当前最稳的情绪结构。",
      performance: contentPerformance(
        "2026-03-18T21:40:00+08:00",
        98000,
        15400,
        520,
        740,
        ["像在写我", "求第 4 周版本"],
      ),
      whyIncluded: "评论在追后续阶段，说明用户在消费完整阶段路径而不是单句共鸣。",
    },
    {
      contentId: "content-boundary",
      platform: "xiaohongshu",
      authorId: "acct-growth-notes",
      authorName: "女生关系边界课",
      industryId: "industry-emotion",
      topicCluster: "阶段型情绪叙事",
      title: "关系里最消耗你的，不是吵架，是这 1 个边界没立住",
      keywordTokens: ["关系边界", "消耗", "女生"],
      tags: ["女性成长", "关系", "表达"],
      structure: contentStructure("痛点开头", "工具型拆解", "图文", "图文"),
      structureSummary: "强痛点 + 方法感，适合从纯共鸣升级到可执行表达。",
      performance: contentPerformance(
        "2026-03-22T13:10:00+08:00",
        143000,
        16800,
        620,
        970,
        ["怎么开口说", "真的很难做到"],
      ),
      whyIncluded: "说明用户需要的不只是被理解，还想拿走可执行表达。",
    },
    {
      contentId: "content-midlife-reset",
      platform: "xiaohongshu",
      authorId: "acct-midlife-reset",
      authorName: "中年重启手册",
      industryId: "industry-emotion",
      topicCluster: "阶段型情绪叙事",
      title: "40 岁被裁员后，我先做的不是投简历，而是这件事",
      keywordTokens: ["40岁", "被裁员", "重建"],
      tags: ["职场", "情感", "成长"],
      structure: contentStructure("反常识开头", "阶段复盘", "竖屏视频", "60-90s"),
      structureSummary: "人生阶段 + 反常识动作，更容易触发转发和自我代入。",
      performance: contentPerformance(
        "2026-03-19T10:10:00+08:00",
        76000,
        5400,
        410,
        680,
        ["像在说我爸妈", "求后续"],
      ),
      whyIncluded: "证明阶段叙事在更成熟人群里同样有效。",
    },
  ],
};

const MATERNITY_FIXTURE: TrendSeedFixture = {
  id: "maternity",
  matchers: [/母婴/, /育儿/, /宝妈/, /宝宝/],
  trend: {
    trendId: "trend-maternity-problem",
    industryId: "industry-maternity",
    industryName: "母婴育儿",
    platform: "xiaohongshu",
    topicCluster: "月龄问题型育儿内容",
    momentumLabel: "emerging",
    evidenceWindow: {
      startAt: "2026-03-09T00:00:00+08:00",
      endAt: "2026-03-24T23:59:59+08:00",
      lookbackDays: 16,
    },
    kolCount: 8,
    kocCount: 24,
    newCreatorCount: 13,
    similarContentCount: 41,
    growth7d: 16,
    lowFollowerAnomalyRatio: 0.13,
    competitionScore: 69,
    opportunityScore: 58,
    riskScore: 66,
    timingLabel: "问题型需求稳定，但泛热点和泛经验复刻很快",
    whyNow: "只有具体月龄和具体问题词还能持续拿到真实反馈。",
    whyRisky: "泛母婴热搜和热点话题极易撞车，且对可信度要求更高。",
    recommendedAction: "建立问题监控，用具体月龄+具体问题的组合切入。",
    evidence: {
      supportingAccountIds: ["acct-baby-month", "acct-baby-qna", "acct-baby-sleep"],
      supportingContentIds: ["content-baby-cry", "content-month-9", "content-sleep-routine"],
      lowFollowerSampleIds: ["g4"],
    },
    accountTierRuleVersion: "account-tier-rules.v1",
    trendDetectionRuleVersion: "trend-detection.v1",
    scoreEngineVersion: "score-engine.v1",
  },
  tierBreakdown: {
    headKol: 0,
    standardKol: 8,
    strongKoc: 9,
    standardKoc: 15,
  },
  accounts: [
    {
      accountId: "acct-baby-month",
      platform: "xiaohongshu",
      handle: "月龄问题解答簿",
      displayName: "月龄问题解答簿",
      industryId: "industry-maternity",
      tierLabel: "standard_koc",
      performance: accountPerformance(14600, 10.1, 0.24),
      recentTopicClusters: ["9月龄", "辅食", "作息"],
      whyIncluded: "月龄明确的问题型表达，比泛育儿经验更容易沉淀收藏。",
    },
    {
      accountId: "acct-baby-qna",
      platform: "douyin",
      handle: "新手爸妈高频问答",
      displayName: "新手爸妈高频问答",
      industryId: "industry-maternity",
      tierLabel: "strong_koc",
      performance: accountPerformance(22400, 8.3, 0.21),
      recentTopicClusters: ["哭闹", "作息", "辅食"],
      whyIncluded: "说明即时问题词依旧强，但需要真实经验和可执行解法。",
    },
    {
      accountId: "acct-baby-sleep",
      platform: "xiaohongshu",
      handle: "宝宝睡眠记录本",
      displayName: "宝宝睡眠记录本",
      industryId: "industry-maternity",
      tierLabel: "standard_kol",
      performance: accountPerformance(118000, 5.1, 0.13),
      recentTopicClusters: ["睡眠", "作息", "夜醒"],
      whyIncluded: "中腰部账号也在验证“问题 + 记录”结构，而不是追热榜。",
    },
  ],
  contents: [
    {
      contentId: "content-baby-cry",
      platform: "douyin",
      authorId: "acct-baby-qna",
      authorName: "新手爸妈高频问答",
      industryId: "industry-maternity",
      topicCluster: "月龄问题型育儿内容",
      title: "宝宝突然哭闹不止，我先排除的是这 3 个原因",
      keywordTokens: ["哭闹", "原因", "排除"],
      tags: ["母婴", "问题", "解法"],
      structure: contentStructure("强问题开头", "排查清单", "口播", "30-60s"),
      structureSummary: "问题直接开场 + 排查法，是当前最能留住新手父母的结构。",
      performance: contentPerformance(
        "2026-03-18T07:40:00+08:00",
        138000,
        9400,
        690,
        1110,
        ["我家也是这样", "求夜醒版本"],
      ),
      whyIncluded: "说明用户在找的是即时问题解法，不是泛育儿热点。",
    },
    {
      contentId: "content-month-9",
      platform: "xiaohongshu",
      authorId: "acct-baby-month",
      authorName: "月龄问题解答簿",
      industryId: "industry-maternity",
      topicCluster: "月龄问题型育儿内容",
      title: "9 月龄突然不爱吃辅食，先别急着换菜单",
      keywordTokens: ["9月龄", "辅食", "不爱吃"],
      tags: ["母婴", "月龄", "辅食"],
      structure: contentStructure("月龄开头", "误区纠正", "图文", "图文"),
      structureSummary: "月龄限制 + 误区纠正，让内容更像解决问题而不是泛经验。",
      performance: contentPerformance(
        "2026-03-22T09:20:00+08:00",
        76000,
        8200,
        310,
        520,
        ["正好 9 月龄", "收藏了晚上看"],
      ),
      whyIncluded: "验证了“明确月龄”会显著提高内容价值感和收藏率。",
    },
    {
      contentId: "content-sleep-routine",
      platform: "xiaohongshu",
      authorId: "acct-baby-sleep",
      authorName: "宝宝睡眠记录本",
      industryId: "industry-maternity",
      topicCluster: "月龄问题型育儿内容",
      title: "我把宝宝夜醒次数从 5 次降到 2 次，只改了睡前这一步",
      keywordTokens: ["夜醒", "睡前", "次数"],
      tags: ["母婴", "作息", "记录"],
      structure: contentStructure("结果先行", "单变量解释", "图文", "图文"),
      structureSummary: "问题 + 单变量解法，是最接近真实可复制经验的形式。",
      performance: contentPerformance(
        "2026-03-20T21:00:00+08:00",
        92000,
        7400,
        380,
        630,
        ["今晚试试", "求作息表"],
      ),
      whyIncluded: "用户在追求可执行变化，而不是听新的育儿观点。",
    },
  ],
  evidenceGaps: ["低粉异常样本正在积累中，可以先用已有样本快速验证。"],
};

const GENERIC_FIXTURE: TrendSeedFixture = {
  id: "generic",
  matchers: [],
  trend: {
    trendId: "trend-generic-observe",
    industryId: "industry-generic",
    industryName: "泛内容创作",
    platform: "douyin",
    topicCluster: "待验证细分方向",
    momentumLabel: "emerging",
    evidenceWindow: {
      startAt: "2026-03-12T00:00:00+08:00",
      endAt: "2026-03-24T23:59:59+08:00",
      lookbackDays: 12,
    },
    kolCount: 6,
    kocCount: 15,
    newCreatorCount: 9,
    similarContentCount: 24,
    growth7d: 12,
    lowFollowerAnomalyRatio: 0.09,
    competitionScore: 57,
    opportunityScore: 61,
    riskScore: 58,
    timingLabel: "方向有可测空间，但证据还比较稀疏",
    whyNow: "目前更像一个待验证切口，而不是已经成立的成熟机会。",
    whyRisky: "人群、场景和结果承诺还不够清晰，容易停留在泛判断。",
    recommendedAction: "先补证据和监控，不宜直接给高承诺动作。",
    evidence: {
      supportingAccountIds: ["acct-generic-operator", "acct-generic-koc"],
      supportingContentIds: ["content-generic-case", "content-generic-tip"],
      lowFollowerSampleIds: [],
    },
    accountTierRuleVersion: "account-tier-rules.v1",
    trendDetectionRuleVersion: "trend-detection.v1",
    scoreEngineVersion: "score-engine.v1",
  },
  tierBreakdown: {
    headKol: 0,
    standardKol: 6,
    strongKoc: 4,
    standardKoc: 11,
  },
  accounts: [
    {
      accountId: "acct-generic-operator",
      platform: "douyin",
      handle: "内容实验记录",
      displayName: "内容实验记录",
      industryId: "industry-generic",
      tierLabel: "standard_koc",
      performance: accountPerformance(12200, 6.8, 0.16),
      recentTopicClusters: ["选题实验", "评论反馈", "内容结构"],
      whyIncluded: "当前更适合用实验账号和小样确认方向，而不是直接判大机会。",
    },
    {
      accountId: "acct-generic-koc",
      platform: "xiaohongshu",
      handle: "内容观察手记",
      displayName: "内容观察手记",
      industryId: "industry-generic",
      tierLabel: "watch_account",
      performance: accountPerformance(7600, 5.9, 0.12),
      recentTopicClusters: ["细分问题", "选题观察"],
      whyIncluded: "说明当前真正缺的是更窄的人群和问题证据。",
    },
  ],
  contents: [
    {
      contentId: "content-generic-case",
      platform: "douyin",
      authorId: "acct-generic-operator",
      authorName: "内容实验记录",
      industryId: "industry-generic",
      topicCluster: "待验证细分方向",
      title: "把泛问题压成 1 个具体对象后，评论质量立刻变了",
      keywordTokens: ["具体对象", "评论质量", "内容实验"],
      tags: ["内容策略", "实验"],
      structure: contentStructure("案例开头", "前后对比", "口播", "30-60s"),
      structureSummary: "说明方向不是不能做，而是表达还不够窄。",
      performance: contentPerformance(
        "2026-03-21T11:20:00+08:00",
        54000,
        2900,
        180,
        220,
        ["怎么压缩问题", "很有启发"],
      ),
      whyIncluded: "当前最有效的证据，是“问题缩窄之后反馈变强”。",
    },
    {
      contentId: "content-generic-tip",
      platform: "xiaohongshu",
      authorId: "acct-generic-koc",
      authorName: "内容观察手记",
      industryId: "industry-generic",
      topicCluster: "待验证细分方向",
      title: "找到评论区的真实问题，就是你的内容切入点",
      keywordTokens: ["热点", "评论", "问题"],
      tags: ["内容策略", "观察"],
      structure: contentStructure("反建议开头", "判断框架", "图文", "图文"),
      structureSummary: "强调先找真实问题，再决定是否下注。",
      performance: contentPerformance(
        "2026-03-20T16:40:00+08:00",
        32000,
        4100,
        95,
        140,
        ["怎么判断", "这个方法好"],
      ),
      whyIncluded: "说明当前阶段更像判断框架问题，而不是已有强窗口。",
    },
  ],
  evidenceGaps: [
    "当前还缺少稳定的低粉异常样本。",
    "还缺一批明确的人群/场景/评论意图证据来把方向压窄。",
  ],
};

const SEED_FIXTURES: TrendSeedFixture[] = [
  WORKPLACE_FIXTURE,
  PET_FIXTURE,
  FOOD_FIXTURE,
  FITNESS_FIXTURE,
  EMOTION_FIXTURE,
  MATERNITY_FIXTURE,
  GENERIC_FIXTURE,
];

export function selectFixture(brief: PredictionBrief) {
  const haystack = `${brief.industry} ${brief.seedTopic}`.toLowerCase();
  return (
    SEED_FIXTURES.find((fixture) =>
      fixture.matchers.some((matcher) => matcher.test(haystack)),
    ) ?? GENERIC_FIXTURE
  );
}
